#!/bin/bash

file="$1"

if [ $# -eq 0 ]; then
    file="./src/wasm/wasm_loader.wasm"
    echo "No file specified, using default: $file"
fi

if [ ! -f "$file" ]; then
    echo "Error: File '$file' does not exist"
    exit 1
fi

if [[ "$file" != *.wasm ]]; then
    echo "Error: File '$file' is not a .wasm file"
    exit 1
fi

os="$(uname)"

if [ "$os" = "Linux" ]; then
    base64 "$file" > bytes.txt
elif [ "$os" = "Darwin" ]; then
    base64 -i "$file" -o bytes.txt
else
    echo "Could not identify OS \"$os\""
fi

bytesContent=$(cat bytes.txt)
sed -i '' "s|toUint8Array('.*')|toUint8Array('$bytesContent')|g" ./src/wasm/bytes.js

echo "Replaced bytes in ./src/wasm/bytes.ts with content from $file"