name: Update Maps & Items

on:
  push:
  schedule:
    - cron: '*/30 * * * *'

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run scrapers
        run: |
          bun ./cli/scrape/items.js
          bun ./cli/scrape/maps.js

      - name: Check for changes
        run: |
          git diff --quiet ./src/constants/items.js ./src/constants/maps.js || echo "CHANGED=true" >> $GITHUB_ENV

      - name: Commit and push changes
        if: env.CHANGED == 'true'
        run: |
          git config --global user.name "yolkbot"
          git config --global user.email "octocat@github.com"
          git add ./src/constants/items.js ./src/constants/maps.js
          git commit -m "update maps & items" -m "this is an automatic commit that updates map & item data"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
