name: Scrape Data

on:
  workflow_dispatch:
  schedule:
    - cron: '*/45 * * * *'

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run scrapers
        run: |
          ./scrape.sh
          if git status --porcelain ./src/constants | grep .; then
            echo "CHANGED=true" >> $GITHUB_ENV
          fi
          echo $GITHUB_ENV

      - name: Commit and push changes
        if: env.CHANGED == 'true'
        run: |
          git config --global user.name "yolkbot"
          git config --global user.email "octocat@nowhere.com"
          git add .
          git commit -m "data modifications" -m "this is a fully automatic commit"
          git push origin main
